function missionData = missionParameters()
% Create a dictionary for satellite altimetry missions
missionData = dictionary;

missionData('al') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/current-missions/saral/orbit-1.html', ...
    'name', 'Saral/AltiKa 35-day cycle', ...
    'description','European Remote Sensing', ...
    'start_date', [datetime('14-Mar-2013 05:44:50')], ...
    'end_date', [datetime('31-Mar-2015 22:41:26')], ...
    'semi_major_axis', 7159.496, ...
    'longitude_at_equator', 0.125, ...
    'eccentricity', 0.000165, ...
    'inclination', 98.55, ...
    'orbits_per_cycle', 501, ...
    'repeat_cycle', 35.0, ...
    'is_reference_mission', false ...
);

missionData('alg') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/current-missions/saral/orbit-1.html', ...
    'name', 'Saral/AltiKa drifting (geodetic) orbit', ...
    'description','Decaying orbit, no repeat cycle', ...
    'start_date', [datetime('31-Mar-2015 22:53:34')], ...
    'end_date', [datetime('08-Sep-2023 22:47:46')], ...
    'semi_major_axis', 8000.496, ...
    'longitude_at_equator', 0.125, ...
    'eccentricity', 0, ...
    'inclination', 98.55, ...
    'orbits_per_cycle', Inf, ...
    'repeat_cycle', Inf, ...
    'is_reference_mission', false ...
);

missionData('c2') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/current-missions/cryosat.html', ...
    'name', 'Cryosat-2', ...
    'description','Non-repeating orbit', ...
    'start_date', [datetime('16-Jul-2010 00:22:02')], ...
    'end_date', [datetime('31-Jul-2020 11:29:44')], ...
    'semi_major_axis', 6378 + 717, ...
    'longitude_at_equator', 22.7, ...
    'eccentricity', 0, ...
    'inclination', 92.03, ...
    'repeat_cycle', Inf, ...
    'is_reference_mission', false ...
);

missionData('c2n') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/current-missions/cryosat.html', ...
    'name', 'Cryosat-2 new orbit', ...
    'description','Non-repeating orbit. New orbit, but not sure how it differs from previous', ...
    'start_date', [datetime('01-Aug-2020 10:56:11')], ...
    'end_date', [datetime('08-Sep-2023 23:14:41')], ...
    'semi_major_axis', 6378 + 717, ...
    'longitude_at_equator', 0, ...
    'eccentricity', 0, ...
    'inclination', 92.03, ...
    'repeat_cycle', Inf, ...
    'is_reference_mission', false ...
);


missionData('e1g') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/ers-1.html', ...
    'name', 'ERS-1 168-day geodetic orbit', ...
    'description','European Remote Sensing', ...
    'start_date', [datetime('10-Apr-1994 18:20:38')], ...
    'end_date', [datetime('21-Mar-1995 05:40:47')], ...
    'semi_major_axis', 7147.191, ...
    'longitude_at_equator', 25.88, ... % Jeffrey's guess
    'eccentricity', 0.0001042, ... % Jeffrey's guess
    'inclination', 98.491, ...
    'orbits_per_cycle', 2411, ...
    'repeat_cycle', 168.0, ...
    'is_reference_mission', false, ...
    'OrbitTypeNotes', 'ESA sun-synchronous mission, 168-day orbit' ...
);

missionData('e1') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/ers-1.html', ...
    'name', 'ERS-1 35-day cycle', ...
    'start_date', [datetime('23-Oct-1992 22:14:26'), datetime('24-Mar-1995 02:11:31')], ...
    'end_date', [datetime('20-Dec-1993 11:28:02'), datetime('15-May-1995 20:38:41')], ...
    'semi_major_axis', 7159.496, ...
    'longitude_at_equator', 0.2, ... % Jeffrey's guess
    'eccentricity', 0.0001042, ...
    'inclination', 98.543, ...
    'orbits_per_cycle', 501, ...
    'repeat_cycle', 35.0, ...
    'is_reference_mission', false, ...
    'OrbitTypeNotes', 'ESA sun-synchronous mission, 35-day orbit' ...
);


missionData('e2') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/ers-2.html', ...
    'name', 'ERS-2 35-day cycle', ...
    'description','European Remote Sensing', ...
    'start_date', [datetime('15-May-1995 22:11:19')], ...
    'end_date', [datetime('14-May-2002 18:04:55')], ...
    'semi_major_axis', 7159.5, ...
    'longitude_at_equator', 0.05, ... % Jeffrey's guess
    'eccentricity', 0.0001042, ...
    'inclination', 98.543, ...
    'orbits_per_cycle', 501, ...
    'repeat_cycle', 35.0, ...
    'is_reference_mission', false, ...
    'OrbitTypeNotes', 'ESA sun-synchronous mission, 35-day orbit' ...
);

missionData('en') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/envisat/orbit.html', ...
    'name', 'Envisat 35-day cycle', ...
    'start_date', [datetime('17-May-2002 07:23:51')], ...
    'end_date', [datetime('18-Oct-2010 21:26:41')], ...
    'semi_major_axis', 7159.5, ...
    'longitude_at_equator', -25, ... % Jeffrey's guess
    'eccentricity', 0.001165, ...
    'inclination', 98.55, ...
    'orbits_per_cycle', 501, ...
    'repeat_cycle', 35.0, ...
    'is_reference_mission', false, ...
    'OrbitTypeNotes', 'ESA sun-synchronous mission, 35-day orbit' ...
);

missionData('enn') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/envisat/orbit.html', ...
    'name', 'Envisat 30-day cycle', ...
    'start_date', [datetime('26-Oct-2010 07:58:16')], ...
    'end_date', [datetime('08-Apr-2012 10:43:05')], ...
    'semi_major_axis', 7142.0, ...
    'longitude_at_equator', 0.67, ... % Jeffrey's guess
    'eccentricity', 0.001158, ...
    'inclination', 98.55, ...
    'orbits_per_cycle', 431, ...
    'repeat_cycle', 30.0, ...
    'is_reference_mission', false, ...
    'OrbitTypeNotes', 'ESA sun-synchronous mission, 30-day orbit' ...
);

missionData('g2') = struct( ...
    'source','https://www.eoportal.org/satellite-missions/gfo#spacecraft and https://en.wikipedia.org/wiki/Geosat', ...
    'name', 'GFO (Geosat Follow-On) 17-day cycle', ...
    'start_date', [datetime('07-Jan-2000 18:26:58')], ...
    'end_date', [datetime('07-Sep-2008 21:11:17')], ...
    'semi_major_axis', 7146.2, ...
    'longitude_at_equator', 1.08, ... % Jeffrey's guess
    'eccentricity', 0.00398, ...
    'inclination', 108.0596, ...
    'orbits_per_cycle', 244, ...
    'repeat_cycle', 17.0, ...
    'is_reference_mission', false ...
);

missionData('h2a') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/hy-2a.html', ...
    'name', 'HaiYang-2A 14-day cycle', ...
    'start_date', [datetime('12-Apr-2014 02:04:55')], ...
    'end_date', [datetime('15-Mar-2016 22:55:25')], ...
    'semi_major_axis', 7349, ...
    'longitude_at_equator', -122.932, ... % Jeffrey's guess
    'eccentricity', 0, ...
    'inclination', 99.3, ... % 'orbits_per_cycle', 244, ...????
    'repeat_cycle', 14.0, ...
    'is_reference_mission', false ...
);

missionData('h2b') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/current-missions/hy-2b.html', ...
    'name', 'HaiYang-2B 14-day cycle', ...
    'start_date', [datetime('20-Dec-2019 21:44:06')], ...
    'end_date', Inf, ...
    'semi_major_axis', 7351, ...
    'longitude_at_equator', -37.1504, ... % Jeffrey's guess
    'eccentricity', 0, ...
    'inclination', 99.3, ... % 'orbits_per_cycle', 244, ...????
    'repeat_cycle', 14.0, ...
    'is_reference_mission', false ...
);

%% Jason-1 entries

missionData('j1g') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/jason-1/orbit-1.html', ...
    'name','Jason-1 geodetic (Long Repeat) orbit', ...
    'start_date', [datetime('07-May-2012 16:04:19')], ...
    'end_date', [datetime('21-Jun-2013 00:51:56')], ...
    'semi_major_axis', 7702.437, ...    % [km] (assumed unchanged)
    'eccentricity', 0.000200, ...
    'inclination', 66.042, ...           % [deg]
    'longitude_at_equator', -51.22, ... % jeffrey's estimate (ascending)
    'repeat_cycle', Inf, ...            % [days] Originally had 406.0 here, but that's the entire record.
    'is_reference_mission', false ...
);

missionData('j1') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/jason-1/orbit-1.html', ...
    'name', 'Jason-1 10-day cycle', ...
    'start_date', [datetime('24-Apr-2002 08:56:09')], ...
    'end_date', [datetime('19-Oct-2008 04:56:59')], ...
    'semi_major_axis', 7714.4278, ...
    'eccentricity', 0.000095, ...
    'inclination', 66.039, ...
    'orbits_per_cycle', 254, ...
    'longitude_at_equator', 99.9242, ...
    'repeat_cycle', 9.9156, ...
    'is_reference_mission', true ...
);

missionData('j1n') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/jason-1/orbit-1.html', ...
    'name','Jason-1 interleaved orbit', ...
    'start_date', [datetime('10-Feb-2009 18:01:39')], ...
    'end_date', [datetime('03-Mar-2012 12:59:12')], ...
    'semi_major_axis', 7714.4280, ...    % [km] (≈+0.0002 km adjustment)
    'eccentricity', 0.000095, ...
    'inclination', 66.039, ...           % [deg]
    'orbits_per_cycle', 254, ...
    'longitude_at_equator', 98.51, ... % jeffrey's estimate (ascending)
    'repeat_cycle', 9.9156, ...          % [days]
    'is_reference_mission', false ...
    );


%% Jason-2 entries

% j2g: OSTM/Jason-2 on its long-repeat (geodetic) orbit
missionData('j2g') = struct( ...
    'source', 'https://www.aviso.altimetry.fr/en/missions/past-missions/jason-2/orbit.html', ...
    'name', 'Jason-2 geodetic (Long Repeat) orbit', ...
    'start_date', [datetime('11-Jul-2017 11:11:25')], ...
    'end_date', [datetime('14-Sep-2017 06:06:59')], ...
    'semi_major_axis', 7702.0000, ...           % [km]
    'eccentricity', 0.000010, ...
    'inclination', 66.039, ...                  % [deg]
    'longitude_at_equator', 86.05, ... % jeffrey's estimate (ascending)
    'repeat_cycle', Inf, ...                    % [days]
    'is_reference_mission', false ...
);

% j2: OSTM/Jason-2 on its default 10-day (exact-repeat) orbit
missionData('j2') = struct( ...
    'source', 'https://www.aviso.altimetry.fr/en/missions/past-missions/jason-2/orbit.html', ...
    'name', 'Jason-2 10-day cycle', ...
    'start_date', [datetime('19-Oct-2008 05:11:39')], ...
    'end_date', [datetime('26-May-2016 14:12:39')], ...
    'semi_major_axis', 7714.4278, ...           % [km]
    'eccentricity', 0.000095, ...
    'inclination', 66.039, ...                  % [deg]
    'orbits_per_cycle', 254, ...
    'longitude_at_equator', 99.9242, ...
    'repeat_cycle', 9.9156, ...                 % [days]
    'is_reference_mission', true ...
    );

% j2n: OSTM/Jason-2 on its interleaved 10-day orbit
missionData('j2n') = struct( ...
    'source', 'https://www.aviso.altimetry.fr/en/missions/past-missions/jason-2/orbit.html', ...
    'name', 'Jason-2 Interleaved Orbit', ...
    'start_date', [datetime('17-Oct-2016 09:02:07')], ...
    'end_date', [datetime('03-Apr-2017 22:31:09')], ...
    'semi_major_axis', 7714.4278, ...           % [km]
    'eccentricity', 0.000095, ...
    'inclination', 66.039, ...                  % [deg]
    'orbits_per_cycle', 254, ...                % (typically one orbit fewer than the default)
    'longitude_at_equator', (98.51), ... % jeffrey's estimate (ascending)
    'repeat_cycle', 9.9156, ...                 % [days]
    'is_reference_mission', false ...
    );

%% Jason-3 entries

% j3: Jason-3 on its default 10-day (exact-repeat) orbit
missionData('j3') = struct( ...
    'source', 'https://www.aviso.altimetry.fr/en/missions/jason-3/default-orbit.html', ...
    'name', 'Jason-3 10-day cycle', ...
    'start_date', [datetime('26-May-2016 14:14:03')], ...
    'end_date', [datetime('09-Feb-2022 22:40:04')], ...
    'semi_major_axis', 7714.4278, ...           % [km]
    'eccentricity', 0.000095, ...               % (or 0.000098; values are nearly identical)
    'inclination', 66.039, ...                  % [deg]
    'orbits_per_cycle', 254, ...
    'longitude_at_equator', (99.9242), ...
    'repeat_cycle', 9.9156, ...                 % [days]
    'is_reference_mission', true ...
);

% j3n: Jason-3 on its interleaved 10-day orbit
missionData('j3n') = struct( ...
    'source', 'https://www.aviso.altimetry.fr/en/missions/jason-3/interleaved-orbit.html', ...
    'name', 'Jason-3 Interleaved Orbit', ...
    'start_date', [datetime('28-Feb-2021 23:14:50')], ...
    'end_date', Inf, ...
    'semi_major_axis', 7714.4278, ...           % [km]
    'eccentricity', 0.000095, ...
    'inclination', 66.039, ...                  % [deg]
    'orbits_per_cycle', 254, ...                % (adjusted for interleaving)
    'longitude_at_equator', (98.51), ... % jeffrey's estimate (ascending)
    'repeat_cycle', 9.9156, ...                 % [days]
    'is_reference_mission', false ...
);

%% Sentinel-3A entries

missionData('s3a') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/current-missions/sentinel-3a/orbit.html', ...
    'name', 'Sentinel-3A', ...
    'start_date', [datetime('01-Mar-2016 14:39:51')], ...
    'end_date', Inf, ...
    'semi_major_axis', 7177.926540, ...
    'longitude_at_equator', 0.55, ... % jeffrey's estimate
    'eccentricity', 0.001148, ...
    'inclination', 98.645589, ...
    'orbits_per_cycle', 770/2, ...
    'repeat_cycle', 27.0, ...
    'is_reference_mission', false ...
);

%% Sentinel-3B entries

missionData('s3b') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/current-missions/sentinel-3b.html', ...
    'name', 'Sentinel-3B', ...
    'start_date', [datetime('26-Nov-2018 23:42:07')], ...
    'end_date', Inf, ...
    'semi_major_axis', 7177.926540, ...
    'longitude_at_equator', 0.17, ... % jeffrey's estimate
    'eccentricity', 0.001148, ...
    'inclination', 98.645589, ...
    'orbits_per_cycle', 770/2, ...
    'repeat_cycle', 27.0, ...
    'is_reference_mission', false ...
);

%% Sentinel-6A entries

missionData('s6a') = struct( ...
    'source', 'https://www.aviso.altimetry.fr/en/missions/current-missions/sentinel-6mf.html', ...
    'name', 'Sentinel-6 Michael Freilich 10-day cycle', ...
    'start_date', [datetime('09-Feb-2022 23:13:23')], ...
    'end_date', Inf, ...
    'semi_major_axis', 7714.4278, ...           % [km]
    'eccentricity', 0.000095, ...               % (or 0.000098; values are nearly identical)
    'inclination', 66.039, ...                  % [deg]
    'orbits_per_cycle', 254, ...
    'longitude_at_equator', 99.9242, ...
    'repeat_cycle', 9.9156, ...                 % [days]
    'is_reference_mission', true ...
);

%% SWOT

missionData('swon') = struct( ...
    'source', 'https://www.aviso.altimetry.fr/en/missions/current-missions/swot.html', ...
    'name', 'SWOT 21-day cycle', ...
    'start_date', [datetime('21-Jul-2023 00:00:00')], ...
    'end_date', Inf, ...
    'semi_major_axis', 7268.7189, ...           % [km]
    'longitude_at_equator', 0.0, ... % Filler! I have not checked this
    'eccentricity', 0.00105, ...               
    'inclination', 77.6, ...                  % [deg]
    'orbits_per_cycle', 292, ...
    'repeat_cycle', 20.86455, ...                 % [days]
    'is_reference_mission', false ...
);

%% TOPEX/Poseidon entries

missionData('tp') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/topex-poseidon/orbits.html', ...
    'name', 'TOPEX/Poseidon', ...
    'start_date', [datetime('03-Oct-1992 01:42:25')], ...
    'end_date', [datetime('24-Apr-2002 07:56:09')], ...
    'semi_major_axis', 7714.4278, ...
    'eccentricity', 0.000095, ...
    'inclination', 66.039, ...
    'orbits_per_cycle', 254, ...
    'longitude_at_equator', 98.51, ...
    'repeat_cycle', 9.9156, ...
    'is_reference_mission', true, ...
    'OrbitTypeNotes', 'Joint NASA/CNES mission ("reference" mission)' ...
);

missionData('tpn') = struct( ...
    'source','https://www.aviso.altimetry.fr/en/missions/past-missions/topex-poseidon/orbits.html', ...
    'name', 'TOPEX/Poseidon', ...
    'start_date', [datetime('20-Sep-2002 02:46:40')], ...
    'end_date', [datetime('08-Oct-2005 23:49:29')], ...
    'semi_major_axis', 7714.4278, ...
    'eccentricity', 0.000095, ...
    'inclination', 66.039, ...
    'orbits_per_cycle', 254, ...
    'longitude_at_equator', 99.9242, ...
    'repeat_cycle', 9.9156, ...
    'is_reference_mission', false, ...
    'OrbitTypeNotes', 'Joint NASA/CNES mission ("reference" mission)' ...
);

end