classdef TestAlongTrackPortableRunBundle < matlab.unittest.TestCase

    properties
        tempFolder string
    end

    methods (TestMethodSetup)
        function createTemporaryFolder(testCase)
            fixture = testCase.applyFixture(matlab.unittest.fixtures.TemporaryFolderFixture);
            testCase.tempFolder = string(fixture.Folder);
        end
    end

    methods (Test)
        function authoringPreservesExactConstructionWithoutFutureTracks(testCase)
            model = TestAlongTrackPortableRunBundle.fixtureModel();
            sourcePath = fullfile(testCase.tempFolder,"portable-j3.nc");
            bundle = authorAlongTrackPortableRunBundle( ...
                model,sourcePath,"j3",initialTime=0,integrationFinalTime=100.5, ...
                finalTime=10000,missionEpochSeconds=-21678, ...
                sampleIntervalSeconds=1,checkpointIntervalSeconds=100.5, ...
                fieldNames=["ssh","ssu","ssv"],interpolation="spline", ...
                observerIdentifier="test-observer", ...
                fileIdentifier="test-file",groupIdentifier="test-output", ...
                integrationMethod="adaptive-rk23",initialStep=10,maximumStep=60);

            testCase.verifyTrue(isfile(bundle.modelFile));
            testCase.verifyTrue(isfile(bundle.requestFile));
            testCase.verifyEqual(bundle.fileIdentifier,"test-file");
            testCase.verifyEqual(bundle.groupIdentifier,"test-output");
            testCase.verifyEqual(bundle.scheduleTypeIdentifier,"WVAlongTrackSchedule");
            testCase.verifyEqual(bundle.scheduleContractVersion,uint32(1));
            testCase.verifyEqual(bundle.observerIdentifier,"test-observer");
            testCase.verifyEqual(bundle.observerTypeIdentifier,"WVAlongTrackObservingSystem");
            testCase.verifyEqual(bundle.observerContractVersion,uint32(1));
            testCase.verifyEqual(bundle.fieldNames,["ssh","ssu","ssv"]);
            testCase.verifyEqual(bundle.interpolation,"spline");

            catalog = AlongTrackSimulator.missionParametersCatalog();
            resolved = AlongTrackSimulator().missionParameters("j3");
            configuration = bundle.sourceConfiguration;
            testCase.verifyEqual(configuration.semiMajorAxisKm,catalog("j3").semi_major_axis);
            testCase.verifyEqual(configuration.resolvedSemiMajorAxisKm,resolved.semi_major_axis);
            testCase.verifyEqual(configuration.eccentricity,resolved.eccentricity);
            testCase.verifyEqual(configuration.inclinationDegrees,resolved.inclination);
            testCase.verifyEqual(configuration.ascendingNodeLongitudeDegrees, ...
                resolved.longitude_at_equator);
            testCase.verifyEqual(configuration.passesPerCycle,resolved.passes_per_cycle);
            testCase.verifyEqual(configuration.missionEpochSeconds,-21678);
            testCase.verifyEqual(configuration.windowWidthMeters,model.wvt.Lx);
            testCase.verifyEqual(configuration.windowHeightMeters,model.wvt.Ly);
            testCase.verifyEqual(configuration.centerLatitudeDegrees,model.wvt.latitude);
            testCase.verifyEqual(configuration.centerLongitudeDegrees,0);
            testCase.verifyTrue(configuration.lowerLeftOrigin);
            testCase.verifyEqual(configuration.sampleIntervalSeconds,1);

            groupPath = "/test-output";
            info = ncinfo(bundle.modelFile,groupPath);
            timeDimension = info.Dimensions(strcmp({info.Dimensions.Name},'t'));
            sampleDimension = info.Dimensions(strcmp({info.Dimensions.Name},'sample'));
            testCase.verifyEqual(timeDimension.Length,0);
            testCase.verifyEqual(sampleDimension.Length,0, ...
                "Portable authoring must not serialize a future trajectory.");
            testCase.verifyEqual(string(ncreadatt(bundle.modelFile,"/", ...
                "portableFileIdentifier")),"test-file");
            testCase.verifyEqual(string(ncreadatt(bundle.modelFile,groupPath, ...
                "portableIdentifier")),"test-output");
            testCase.verifyEqual(string(ncreadatt(bundle.modelFile,groupPath, ...
                "portableScheduleTypeIdentifier")),"WVAlongTrackSchedule");
            testCase.verifyEqual(ncreadatt(bundle.modelFile,groupPath, ...
                "portableScheduleContractVersion"),uint32(1));
            observerPath = groupPath + "/observingSystems/observingSystems-1";
            testCase.verifyEqual(string(ncreadatt(bundle.modelFile,observerPath, ...
                "AnnotatedClass")),"WVAlongTrackObservingSystem");
            testCase.verifyEqual(string(ncreadatt(bundle.modelFile,observerPath, ...
                "portableIdentifier")),"test-observer");
            testCase.verifyEqual(ncreadatt(bundle.modelFile,observerPath, ...
                "portableObserverContractVersion"),uint32(1));
            testCase.verifyGreaterThan(strlength(string(ncreadatt(bundle.modelFile, ...
                groupPath,"portableScheduleConfiguration"))),100);
            testCase.verifyGreaterThan(strlength(string(ncreadatt(bundle.modelFile, ...
                observerPath, ...
                "portableObserverConfiguration"))),100);

            request = jsondecode(fileread(bundle.requestFile));
            testCase.verifyEqual(string(request.schemaIdentifier), ...
                "wave-vortex-run-request-v1");
            testCase.verifyEqual(string(request.integration.method),"adaptive-rk23");
            testCase.verifyEqual(request.integration.finalTime,100.5);
            testCase.verifyEqual(string(request.output.policy),"create");
            testCase.verifyEqual(string(request.execution.fftProvider),"reference");
            testCase.verifyEqual(request.execution.threads,1);
        end

        function retainedAuthoringStorageIsDurationIndependent(testCase)
            for missionName = ["j3","alg"]
                shortModel = TestAlongTrackPortableRunBundle.fixtureModel();
                longModel = TestAlongTrackPortableRunBundle.fixtureModel();
                shortStem = missionName + "-short";
                longStem = missionName + "-long";
                shortBundle = authorAlongTrackPortableRunBundle( ...
                    shortModel,fullfile(testCase.tempFolder,shortStem + ".nc"), ...
                    missionName,finalTime=1000,integrationFinalTime=100, ...
                    requestPath=fullfile(testCase.tempFolder,shortStem + ".json"));
                longBundle = authorAlongTrackPortableRunBundle( ...
                    longModel,fullfile(testCase.tempFolder,longStem + ".nc"), ...
                    missionName,finalTime=10*365*86400,integrationFinalTime=100, ...
                    requestPath=fullfile(testCase.tempFolder,longStem + ".json"));

                shortInfo = dir(shortBundle.modelFile);
                longInfo = dir(longBundle.modelFile);
                testCase.verifyEqual(shortInfo.bytes,longInfo.bytes, ...
                    missionName + " authoring storage grew with duration.");
                groupPath = "/" + missionName + "-along-track-output";
                for dimensionName = ["t","sample"]
                    testCase.verifyEqual( ...
                        TestAlongTrackPortableRunBundle.dimensionLength( ...
                        shortBundle.modelFile,groupPath,dimensionName),0);
                    testCase.verifyEqual( ...
                        TestAlongTrackPortableRunBundle.dimensionLength( ...
                        longBundle.modelFile,groupPath,dimensionName),0);
                end
                for attributeName = ["portableScheduleConfiguration", ...
                        "portableObserverConfiguration", ...
                        "portableObservationSchemaManifest"]
                    if attributeName == "portableScheduleConfiguration"
                        attributePath = groupPath;
                    else
                        attributePath = groupPath + ...
                            "/observingSystems/observingSystems-1";
                    end
                    shortAttribute = ncreadatt( ...
                        shortBundle.modelFile,attributePath,attributeName);
                    longAttribute = ncreadatt( ...
                        longBundle.modelFile,attributePath,attributeName);
                    testCase.verifyEqual(string(shortAttribute), ...
                        string(longAttribute), ...
                        missionName + " retained record size grew with duration.");
                end
            end
        end

        function authoringFailurePreservesExistingFiles(testCase)
            model = TestAlongTrackPortableRunBundle.fixtureModel();
            sourcePath = fullfile(testCase.tempFolder,"protected.nc");
            TestAlongTrackPortableRunBundle.writeText(sourcePath,"protected source");
            before = TestAlongTrackPortableRunBundle.fileBytes(sourcePath);
            testCase.verifyError(@() authorAlongTrackPortableRunBundle( ...
                model,sourcePath,"j3",finalTime=100), ...
                "AlongTrackSimulator:PortableAuthoringTargetExists");
            testCase.verifyEqual(TestAlongTrackPortableRunBundle.fileBytes(sourcePath),before);

            destinationPath = fullfile(testCase.tempFolder,"protected-output.nc");
            TestAlongTrackPortableRunBundle.writeText(destinationPath,"protected destination");
            destinationBefore = TestAlongTrackPortableRunBundle.fileBytes(destinationPath);
            testCase.verifyError(@() authorAlongTrackPortableRunBundle( ...
                model,fullfile(testCase.tempFolder,"new.nc"),"j3", ...
                finalTime=100,destinationPath=destinationPath), ...
                "AlongTrackSimulator:PortableDestinationExists");
            testCase.verifyEqual(TestAlongTrackPortableRunBundle.fileBytes(destinationPath), ...
                destinationBefore);
        end

        function extendedRunnerMatchesAuthoritativeMATLAB(testCase)
            runner = string(getenv('ATS4_EXTENDED_RUNNER'));
            testCase.assumeNotEmpty(runner, ...
                "Set ATS4_EXTENDED_RUNNER to run the MATLAB/C++ parity gate.");
            testCase.assertTrue(isfile(runner),"ATS4_EXTENDED_RUNNER does not exist.");

            repositoryRoot = fileparts(fileparts(mfilename('fullpath')));
            fixtureFolder = fullfile(repositoryRoot,"cpp","tests","data","ats4");
            definitions = TestAlongTrackPortableRunBundle.parityDefinitions();
            for iDefinition = 1:numel(definitions)
                TestAlongTrackPortableRunBundle.verifyParityCase( ...
                    testCase,runner,fixtureFolder,definitions(iDefinition));
            end
        end
    end

    methods (Static,Access=private)
        function definitions = parityDefinitions()
            definitions = [ ...
                struct(name="repeating",missionName="j3", ...
                    missionEpochSeconds=-21678, ...
                    fileIdentifier="repeating", ...
                    groupIdentifier="ats4-repeating-output", ...
                    observerIdentifier="ats4-repeating-observer", ...
                    interpolation="linear",integrator="fixed-rk4", ...
                    initialTime=0,integrationFinalTime=100.5,initialStep=10, ...
                    maximumStep=NaN,relativeTolerance=NaN, ...
                    absoluteToleranceScale=NaN), ...
                struct(name="geodetic",missionName="alg", ...
                    missionEpochSeconds=-1437.75, ...
                    fileIdentifier="geodetic", ...
                    groupIdentifier="ats4-geodetic-output", ...
                    observerIdentifier="ats4-geodetic-observer", ...
                    interpolation="spline",integrator="adaptive-rk23", ...
                    initialTime=0,integrationFinalTime=100.5,initialStep=10, ...
                    maximumStep=60,relativeTolerance=1e-6, ...
                    absoluteToleranceScale=1e-9)];
        end

        function verifyParityCase(testCase,runner,fixtureFolder,definition)
            sourcePath = fullfile(fixtureFolder, ...
                "matlab-authored-" + definition.name + ".nc");
            request = jsondecode(fileread(fullfile(fixtureFolder, ...
                "matlab-authored-" + definition.name + "-request.json")));
            destinationPath = fullfile(testCase.tempFolder, ...
                definition.name + "-parity-output.nc");
            reportPath = fullfile(testCase.tempFolder, ...
                definition.name + "-parity-report.json");
            request.modelFiles = {char(sourcePath)};
            request.output.destinations.(definition.name) = char(destinationPath);
            request.report = char(reportPath);
            requestPath = fullfile(testCase.tempFolder, ...
                definition.name + "-parity-request.json");
            TestAlongTrackPortableRunBundle.writeText( ...
                requestPath,jsonencode(request,PrettyPrint=true));
            sourceBefore = TestAlongTrackPortableRunBundle.fileBytes(sourcePath);

            command = sprintf('"%s" --request "%s"',runner,requestPath);
            [status,output] = ...
                TestAlongTrackPortableRunBundle.runPortableExecutable(command);
            testCase.assertEqual(status,0,output);
            testCase.verifyEqual(TestAlongTrackPortableRunBundle.fileBytes(sourcePath), ...
                sourceBefore,"The runner mutated the " + definition.name + ...
                " MATLAB-authored source bundle.");

            report = jsondecode(fileread(reportPath));
            testCase.verifyEqual(string(report.status),"complete");
            testCase.verifyEqual(string(report.integrator.id),definition.integrator);
            if definition.integrator == "adaptive-rk23"
                testCase.verifyGreaterThan(report.integrator.denseOutputEvaluationCount,0);
            else
                testCase.verifyEqual(report.integrator.denseOutputEvaluationCount,0);
            end

            ats = AlongTrackSimulator();
            missionTime = 0:30000;
            alongtrack = ats.projectedPointsForMissionWithName( ...
                definition.missionName,Lx=8e6,Ly=8e6,lat0=24,lon0=0, ...
                time=missionTime);
            passes = AlongTrackSimulator.convertAlongTrackStructureToPass(alongtrack);
            triggerTimes = cellfun(@(pass) ...
                pass.t(1) + definition.missionEpochSeconds,passes);
            selected = find(triggerTimes >= definition.initialTime & ...
                triggerTimes <= definition.integrationFinalTime);
            testCase.assertNumElements(selected,1, ...
                "The MATLAB authority did not find exactly one " + ...
                definition.name + " occurrence in the runner interval.");
            pass = passes{selected};
            expectedTriggerTime = triggerTimes(selected);
            expectedTime = reshape(pass.t + definition.missionEpochSeconds,[],1);
            expectedX = reshape(pass.x,[],1);
            expectedY = reshape(pass.y,[],1);

            group = "/" + definition.groupIdentifier + "/";
            actualTriggerTime = ncread(destinationPath,group + "t");
            actualTime = ncread(destinationPath,group + "sample-time");
            actualX = ncread(destinationPath,group + "x");
            actualY = ncread(destinationPath,group + "y");
            [triggerAbsolute,triggerNormalized] = ...
                TestAlongTrackPortableRunBundle.errors( ...
                actualTriggerTime,expectedTriggerTime);
            [timeAbsolute,timeNormalized] = TestAlongTrackPortableRunBundle.errors( ...
                actualTime,expectedTime);
            [xAbsolute,xNormalized] = TestAlongTrackPortableRunBundle.errors( ...
                actualX,expectedX);
            [yAbsolute,yNormalized] = TestAlongTrackPortableRunBundle.errors( ...
                actualY,expectedY);

            parityModel = TestAlongTrackPortableRunBundle.fixtureModelAtOccurrence( ...
                definition,expectedTriggerTime);
            [expectedSSH,expectedSSU,expectedSSV] = ...
                parityModel.wvt.variableAtPositionWithName( ...
                reshape(pass.x,1,[]),reshape(pass.y,1,[]),[], ...
                'ssh','ssu','ssv', ...
                interpolationMethod=char(definition.interpolation));
            actualSSH = ncread(destinationPath,group + "ssh");
            actualSSU = ncread(destinationPath,group + "ssu");
            actualSSV = ncread(destinationPath,group + "ssv");
            [sshAbsolute,sshNormalized] = TestAlongTrackPortableRunBundle.errors( ...
                actualSSH,reshape(expectedSSH,[],1));
            [ssuAbsolute,ssuNormalized] = TestAlongTrackPortableRunBundle.errors( ...
                actualSSU,reshape(expectedSSU,[],1));
            [ssvAbsolute,ssvNormalized] = TestAlongTrackPortableRunBundle.errors( ...
                actualSSV,reshape(expectedSSV,[],1));

            absoluteMaxima = [triggerAbsolute,timeAbsolute,xAbsolute,yAbsolute, ...
                sshAbsolute,ssuAbsolute,ssvAbsolute];
            normalizedMaxima = [triggerNormalized,timeNormalized,xNormalized,yNormalized, ...
                sshNormalized,ssuNormalized,ssvNormalized];
            testCase.verifyLessThanOrEqual(normalizedMaxima,1e-12);
            testCase.verifyEqual(ncread(destinationPath, ...
                group + "repeat-cycle-index"),int64(0));
            testCase.verifyEqual(ncread(destinationPath, ...
                group + "first-sample-index"),int64(pass.t(1)));
            testCase.verifyEqual(ncread(destinationPath, ...
                group + "sample-count"),int64(numel(expectedTime)));
            TestAlongTrackPortableRunBundle.verifyPersistedSchemaAndConfiguration( ...
                testCase,sourcePath,destinationPath,definition,1,numel(expectedTime));
            fprintf("ATS4_PARITY %s absolute=[%s] normalized=[%s]\n", ...
                definition.name, ...
                strjoin(compose('%.17g',absoluteMaxima),','), ...
                strjoin(compose('%.17g',normalizedMaxima),','));

            created = TestAlongTrackPortableRunBundle.persistedValues( ...
                destinationPath,group);
            future = find(triggerTimes > definition.integrationFinalTime,1);
            testCase.assertNotEmpty(future, ...
                "The MATLAB authority did not find a later " + ...
                definition.name + " occurrence for restart parity.");
            laterPass = passes{future};
            laterTriggerTime = triggerTimes(future);
            appendRequest = request;
            appendRequest.modelFiles = {char(destinationPath)};
            appendRequest.integration.finalTime = laterTriggerTime;
            appendRequest.output.policy = 'append';
            appendRequest.output.destinations = struct();
            appendReportPath = fullfile(testCase.tempFolder, ...
                definition.name + "-append-report.json");
            appendRequest.report = char(appendReportPath);
            appendRequestPath = fullfile(testCase.tempFolder, ...
                definition.name + "-append-request.json");
            TestAlongTrackPortableRunBundle.writeText( ...
                appendRequestPath,jsonencode(appendRequest,PrettyPrint=true));

            appendCommand = sprintf('"%s" --request "%s"', ...
                runner,appendRequestPath);
            [appendStatus,appendOutput] = ...
                TestAlongTrackPortableRunBundle.runPortableExecutable(appendCommand);
            testCase.assertEqual(appendStatus,0,appendOutput);
            testCase.verifyEqual( ...
                TestAlongTrackPortableRunBundle.fileBytes(sourcePath), ...
                sourceBefore,"Append/restart mutated the " + definition.name + ...
                " MATLAB-authored source bundle.");
            appendReport = jsondecode(fileread(appendReportPath));
            testCase.verifyEqual(string(appendReport.status),"complete");
            testCase.verifyEqual(string(appendReport.integrator.id), ...
                definition.integrator);

            appended = TestAlongTrackPortableRunBundle.persistedValues( ...
                destinationPath,group);
            testCase.assertNumElements(appended.triggerTime,2);
            testCase.verifyEqual(appended.triggerTime(1),created.triggerTime);
            testCase.verifyEqual(appended.scheduleOrdinal,int64([0;1]));
            testCase.verifyEqual(appended.scheduleCursor(1), ...
                created.scheduleCursor);
            testCase.verifyNotEqual(appended.scheduleCursor(2), ...
                appended.scheduleCursor(1));
            testCase.verifyGreaterThan(strlength(appended.scheduleCursor(2)),0);
            testCase.verifyEqual(appended.sampleTime(1:numel(created.sampleTime)), ...
                created.sampleTime);
            testCase.verifyEqual(appended.x(1:numel(created.x)),created.x);
            testCase.verifyEqual(appended.y(1:numel(created.y)),created.y);
            testCase.verifyEqual(appended.ssh(1:numel(created.ssh)),created.ssh);
            testCase.verifyEqual(appended.ssu(1:numel(created.ssu)),created.ssu);
            testCase.verifyEqual(appended.ssv(1:numel(created.ssv)),created.ssv);

            laterSampleCount = numel(laterPass.t);
            laterStart = numel(created.sampleTime) + 1;
            laterIndices = laterStart:(laterStart + laterSampleCount - 1);
            laterExpectedTime = reshape( ...
                laterPass.t + definition.missionEpochSeconds,[],1);
            laterExpectedX = reshape(laterPass.x,[],1);
            laterExpectedY = reshape(laterPass.y,[],1);
            [laterTriggerAbsolute,laterTriggerNormalized] = ...
                TestAlongTrackPortableRunBundle.errors( ...
                appended.triggerTime(2),laterTriggerTime);
            [laterTimeAbsolute,laterTimeNormalized] = ...
                TestAlongTrackPortableRunBundle.errors( ...
                appended.sampleTime(laterIndices),laterExpectedTime);
            [laterXAbsolute,laterXNormalized] = ...
                TestAlongTrackPortableRunBundle.errors( ...
                appended.x(laterIndices),laterExpectedX);
            [laterYAbsolute,laterYNormalized] = ...
                TestAlongTrackPortableRunBundle.errors( ...
                appended.y(laterIndices),laterExpectedY);

            laterModel = ...
                TestAlongTrackPortableRunBundle.fixtureModelAfterContinuation( ...
                definition,laterTriggerTime);
            [laterExpectedSSH,laterExpectedSSU,laterExpectedSSV] = ...
                laterModel.wvt.variableAtPositionWithName( ...
                reshape(laterPass.x,1,[]),reshape(laterPass.y,1,[]),[], ...
                'ssh','ssu','ssv', ...
                interpolationMethod=char(definition.interpolation));
            [laterSSHAbsolute,laterSSHNormalized] = ...
                TestAlongTrackPortableRunBundle.errors( ...
                appended.ssh(laterIndices),reshape(laterExpectedSSH,[],1));
            [laterSSUAbsolute,laterSSUNormalized] = ...
                TestAlongTrackPortableRunBundle.errors( ...
                appended.ssu(laterIndices),reshape(laterExpectedSSU,[],1));
            [laterSSVAbsolute,laterSSVNormalized] = ...
                TestAlongTrackPortableRunBundle.errors( ...
                appended.ssv(laterIndices),reshape(laterExpectedSSV,[],1));

            laterAbsoluteMaxima = [laterTriggerAbsolute,laterTimeAbsolute, ...
                laterXAbsolute,laterYAbsolute,laterSSHAbsolute, ...
                laterSSUAbsolute,laterSSVAbsolute];
            laterNormalizedMaxima = [laterTriggerNormalized, ...
                laterTimeNormalized,laterXNormalized,laterYNormalized, ...
                laterSSHNormalized,laterSSUNormalized,laterSSVNormalized];
            testCase.verifyLessThanOrEqual(laterNormalizedMaxima,1e-12);
            expectedCounts = int64([numel(expectedTime);laterSampleCount]);
            testCase.verifyEqual(appended.repeatCycleIndex,int64([0;0]));
            testCase.verifyEqual(appended.firstSampleIndex, ...
                int64([pass.t(1);laterPass.t(1)]));
            testCase.verifyEqual(appended.sampleCount,expectedCounts);
            testCase.verifyEqual(appended.committedSample, ...
                cumsum(expectedCounts));
            restartTimes = ncread(destinationPath,"/portable-restart/t");
            checkpointInitialTime = ncread(destinationPath, ...
                "/portable-restart/initialTime");
            checkpointInterval = ncread(destinationPath, ...
                "/portable-restart/outputInterval");
            expectedCheckpointTime = checkpointInitialTime + ...
                checkpointInterval*floor((laterTriggerTime - ...
                checkpointInitialTime)/checkpointInterval);
            testCase.verifyEqual(restartTimes(end),expectedCheckpointTime);
            testCase.verifyLessThanOrEqual(restartTimes(end),laterTriggerTime);
            TestAlongTrackPortableRunBundle.verifyPersistedSchemaAndConfiguration( ...
                testCase,sourcePath,destinationPath,definition,2, ...
                sum(double(expectedCounts)));
            fprintf("ATS4_RESTART_PARITY %s absolute=[%s] normalized=[%s]\n", ...
                definition.name, ...
                strjoin(compose('%.17g',laterAbsoluteMaxima),','), ...
                strjoin(compose('%.17g',laterNormalizedMaxima),','));
        end

        function model = fixtureModelAtOccurrence(definition,occurrenceTime)
            model = TestAlongTrackPortableRunBundle.fixtureModel();
            if definition.integrator ~= "adaptive-rk23"
                if occurrenceTime ~= model.t
                    error("AlongTrackSimulator:UnsupportedParityIntegrator", ...
                        "The fixed parity fixture must occur at its exact initial state.");
                end
                return
            end
            model.setupIntegrator(integratorType='adaptive',integrator=@ode23, ...
                absTolerance=definition.absoluteToleranceScale, ...
                relTolerance=definition.relativeTolerance);
            odeOptions = odeset(model.odeOptions, ...
                'InitialStep',definition.initialStep, ...
                'MaxStep',definition.maximumStep,'OutputFcn',[]);
            model.wvt.restoreForcingAmplitudes();
            requestedTimes = [definition.initialTime occurrenceTime ...
                definition.integrationFinalTime];
            [times,states] = ode23(@(time,state) model.fluxArray(time,state), ...
                requestedTimes,model.initialConditionsArray,odeOptions);
            occurrenceIndex = find(times == occurrenceTime,1);
            if isempty(occurrenceIndex)
                error("AlongTrackSimulator:MissingMATLABParityOccurrence", ...
                    "MATLAB ode23 did not return the requested occurrence time.");
            end
            model.updateIntegratorValuesFromArray( ...
                times(occurrenceIndex),states(occurrenceIndex,:).');
        end

        function model = fixtureModelAfterContinuation(definition,occurrenceTime)
            model = TestAlongTrackPortableRunBundle.fixtureModel();
            segmentTimes = [definition.integrationFinalTime occurrenceTime];
            if definition.integrator == "fixed-rk4"
                model.wvt.restoreForcingAmplitudes();
                state = model.initialConditionsCellArray();
                currentTime = definition.initialTime;
                for segmentTime = segmentTimes
                    wholeStepFinalTime = currentTime + definition.initialStep* ...
                        floor((segmentTime-currentTime)/definition.initialStep);
                    if wholeStepFinalTime > currentTime
                        integrator = WVArrayIntegrator( ...
                            @(time,value) model.fluxAtTimeCellArray(time,value), ...
                            [currentTime wholeStepFinalTime],state, ...
                            definition.initialStep);
                        state = integrator.currentY;
                        currentTime = wholeStepFinalTime;
                    end
                    if currentTime < segmentTime
                        integrator = WVArrayIntegrator( ...
                            @(time,value) model.fluxAtTimeCellArray(time,value), ...
                            [currentTime segmentTime],state, ...
                            segmentTime-currentTime);
                        state = integrator.currentY;
                        currentTime = segmentTime;
                    end
                    model.updateIntegratorValuesFromCellArray(currentTime,state);
                end
                return
            end

            model.setupIntegrator(integratorType='adaptive',integrator=@ode23, ...
                absTolerance=definition.absoluteToleranceScale, ...
                relTolerance=definition.relativeTolerance);
            odeOptions = odeset(model.odeOptions, ...
                'InitialStep',definition.initialStep, ...
                'MaxStep',definition.maximumStep,'OutputFcn',[]);
            model.wvt.restoreForcingAmplitudes();
            for segmentTime = segmentTimes
                [times,states] = ode23( ...
                    @(time,state) model.fluxArray(time,state), ...
                    [model.t segmentTime],model.initialConditionsArray,odeOptions);
                model.updateIntegratorValuesFromArray( ...
                    times(end),states(end,:).');
            end
        end

        function values = persistedValues(path,group)
            values = struct( ...
                triggerTime=ncread(path,group + "t"), ...
                sampleTime=ncread(path,group + "sample-time"), ...
                x=ncread(path,group + "x"), ...
                y=ncread(path,group + "y"), ...
                ssh=ncread(path,group + "ssh"), ...
                ssu=ncread(path,group + "ssu"), ...
                ssv=ncread(path,group + "ssv"), ...
                scheduleOrdinal=ncread(path,group + ...
                    "portableScheduleOrdinal"), ...
                scheduleCursor=string(ncread(path,group + ...
                    "portableScheduleCursor")), ...
                committedSample=ncread(path,group + ...
                    "portableCommitted_sample"), ...
                repeatCycleIndex=ncread(path,group + "repeat-cycle-index"), ...
                firstSampleIndex=ncread(path,group + "first-sample-index"), ...
                sampleCount=ncread(path,group + "sample-count"));
        end

        function verifyPersistedSchemaAndConfiguration( ...
                testCase,sourcePath,destinationPath,definition, ...
                recordCount,sampleCount)
            groupPath = "/" + definition.groupIdentifier;
            sourceInfo = ncinfo(sourcePath,groupPath);
            destinationInfo = ncinfo(destinationPath,groupPath);
            testCase.verifyEqual(sort(string({destinationInfo.Variables.Name})), ...
                sort(string({sourceInfo.Variables.Name})), ...
                definition.name + " output changed the authored variable set.");
            testCase.verifyEqual(sort(string({destinationInfo.Dimensions.Name})), ...
                sort(string({sourceInfo.Dimensions.Name})), ...
                definition.name + " output changed the authored dimension set.");
            for iDimension = 1:numel(sourceInfo.Dimensions)
                sourceDimension = sourceInfo.Dimensions(iDimension);
                destinationDimension = destinationInfo.Dimensions( ...
                    strcmp({destinationInfo.Dimensions.Name},sourceDimension.Name));
                testCase.verifyEqual(destinationDimension.Unlimited, ...
                    sourceDimension.Unlimited);
                if string(sourceDimension.Name) == "t"
                    testCase.verifyEqual(destinationDimension.Length,recordCount);
                elseif string(sourceDimension.Name) == "sample"
                    testCase.verifyEqual(destinationDimension.Length,sampleCount);
                end
            end
            for iVariable = 1:numel(sourceInfo.Variables)
                sourceVariable = sourceInfo.Variables(iVariable);
                destinationVariable = destinationInfo.Variables( ...
                    strcmp({destinationInfo.Variables.Name},sourceVariable.Name));
                testCase.assertNumElements(destinationVariable,1);
                testCase.verifyEqual(destinationVariable.Datatype,sourceVariable.Datatype);
                testCase.verifyEqual( ...
                    TestAlongTrackPortableRunBundle.dimensionNames( ...
                    destinationVariable.Dimensions), ...
                    TestAlongTrackPortableRunBundle.dimensionNames( ...
                    sourceVariable.Dimensions));
                if ismember(string(sourceVariable.Name), ...
                        ["sample-time","x","y","repeat-cycle-index", ...
                        "first-sample-index","sample-count","ssh","ssu","ssv"])
                    TestAlongTrackPortableRunBundle.verifyAttributesEqual( ...
                        testCase,sourceVariable.Attributes, ...
                        destinationVariable.Attributes,definition.name + ...
                        " variable " + string(sourceVariable.Name));
                end
            end

            timePath = groupPath + "/t";
            testCase.verifyEqual(string(ncreadatt(destinationPath,timePath, ...
                "axis")),"T");
            testCase.verifyEqual(string(ncreadatt(destinationPath,timePath, ...
                "calendar")),"standard");
            testCase.verifyEqual(string(ncreadatt(destinationPath,timePath, ...
                "long_name")),"time");
            testCase.verifyEqual(string(ncreadatt(destinationPath,timePath, ...
                "standard_name")),"time");
            testCase.verifyEqual(string(ncreadatt(destinationPath,timePath, ...
                "units")),"seconds since 1970-01-01 00:00:00");

            testCase.verifyEqual(string(ncreadatt(destinationPath,"/", ...
                "portableFileIdentifier")),definition.fileIdentifier);
            testCase.verifyEqual(ncreadatt(destinationPath,"/", ...
                "portableFileIdentifier"),ncreadatt(sourcePath,"/", ...
                "portableFileIdentifier"));

            groupAttributes = ["portableIdentifier", ...
                "portableScheduleTypeIdentifier","portableScheduleContractVersion", ...
                "portableScheduleConfiguration"];
            for attribute = groupAttributes
                testCase.verifyEqual( ...
                    ncreadatt(destinationPath,groupPath,attribute), ...
                    ncreadatt(sourcePath,groupPath,attribute));
            end
            testCase.verifyEqual(string(ncreadatt(destinationPath,groupPath, ...
                "portableIdentifier")),definition.groupIdentifier);
            testCase.verifyEqual(string(ncreadatt(destinationPath,groupPath, ...
                "portableScheduleTypeIdentifier")),"WVAlongTrackSchedule");
            testCase.verifyEqual(ncreadatt(destinationPath,groupPath, ...
                "portableScheduleContractVersion"),uint32(1));
            observerPath = groupPath + "/observingSystems/observingSystems-1";
            observerAttributes = ["AnnotatedClass","portableIdentifier","name", ...
                "mission","portableObservationSchemaIdentifier", ...
                "portableObservationSchemaVersion","portableObserverContractVersion", ...
                "portableObserverConfiguration","portableObservationSchemaManifest"];
            for attribute = observerAttributes
                testCase.verifyEqual( ...
                    ncreadatt(destinationPath,observerPath,attribute), ...
                    ncreadatt(sourcePath,observerPath,attribute));
            end
            testCase.verifyEqual(string(ncreadatt(destinationPath,observerPath, ...
                "portableIdentifier")),definition.observerIdentifier);
            testCase.verifyEqual(ncreadatt(destinationPath,observerPath, ...
                "portableObserverContractVersion"),uint32(1));
            testCase.verifyEqual(string(ncreadatt(destinationPath,observerPath, ...
                "provider")),"WVAlongTrackObservingSystem");
            testCase.verifyEqual(string(ncreadatt(destinationPath,observerPath, ...
                "contract")),"generic-along-track-occurrence-v1");

            for variable = ["Lx","Ly","Lz","N0","g","isHydrostatic", ...
                    "latitude","planetaryRadius","rho0","rotationRate", ...
                    "shouldAntialias","t0"]
                testCase.verifyEqual(ncread(destinationPath,"/" + variable), ...
                    ncread(sourcePath,"/" + variable));
            end
        end

        function verifyAttributesEqual(testCase,source,destination,context)
            if isempty(source) || isempty(destination)
                testCase.verifyEqual(isempty(destination),isempty(source), ...
                    context + " attributes changed.");
                return
            end
            testCase.verifyEqual(sort(string({destination.Name})), ...
                sort(string({source.Name})),context + " attributes changed.");
            for iAttribute = 1:numel(source)
                destinationAttribute = destination( ...
                    strcmp({destination.Name},source(iAttribute).Name));
                testCase.assertNumElements(destinationAttribute,1);
                testCase.verifyEqual(destinationAttribute.Value,source(iAttribute).Value, ...
                    context + " attribute " + string(source(iAttribute).Name) + ...
                    " changed.");
            end
        end

        function names = dimensionNames(dimensions)
            if isempty(dimensions)
                names = string.empty(1,0);
            else
                names = string({dimensions.Name});
            end
        end

        function model = fixtureModel()
            rng(271828,'twister');
            wvt = WVTransformConstantStratification([8e6 8e6 500],[8 8 5], ...
                N0=5.2e-3,latitude=24,isHydrostatic=true,shouldAntialias=false);
            wvt.initWithRandomFlow(uvMax=1e-3);
            wvt.addForcing(WVAdaptiveDamping(wvt));
            model = WVModel(wvt);
        end

        function lengthValue = dimensionLength(path,groupPath,name)
            info = ncinfo(path,groupPath);
            dimension = info.Dimensions(strcmp({info.Dimensions.Name},name));
            lengthValue = dimension.Length;
        end

        function bytes = fileBytes(path)
            fileID = fopen(path,'rb');
            if fileID == -1
                error("AlongTrackSimulator:TestFileOpenFailed", ...
                    "Could not open '%s'.",path);
            end
            cleanup = onCleanup(@() fclose(fileID));
            bytes = fread(fileID,Inf,'*uint8');
            clear cleanup
        end

        function writeText(path,text)
            fileID = fopen(path,'wt');
            if fileID == -1
                error("AlongTrackSimulator:TestFileOpenFailed", ...
                    "Could not open '%s'.",path);
            end
            cleanup = onCleanup(@() fclose(fileID));
            fprintf(fileID,'%s',text);
            clear cleanup
        end

        function [status,output] = runPortableExecutable(command)
            if isunix && ~ismac
                originalLibraryPath = getenv('LD_LIBRARY_PATH');
                libraryPathCleanup = onCleanup( ...
                    @() setenv('LD_LIBRARY_PATH',originalLibraryPath));
                setenv('LD_LIBRARY_PATH','');
            end
            [status,output] = system(command);
            if exist('libraryPathCleanup','var')
                clear libraryPathCleanup
            end
        end

        function [absoluteMaximum,normalizedMaximum] = errors(actual,expected)
            delta = abs(double(actual(:))-double(expected(:)));
            absoluteMaximum = max(delta,[],'all');
            normalizedMaximum = absoluteMaximum/max(1,max(abs(double(expected)),[],'all'));
        end
    end
end
