function generate_ats4_portable_bundles()
% Generate the MATLAB-authoritative ATS #4 portable runner fixtures.

repositoryRoot = fileparts(fileparts(mfilename('fullpath')));
fixtureFolder = fullfile(repositoryRoot,"cpp","tests","data","ats4");
if ~isfolder(fixtureFolder)
    mkdir(fixtureFolder);
end

rng(271828,'twister');
wvt = WVTransformConstantStratification([8e6 8e6 500],[8 8 5], ...
    N0=5.2e-3,latitude=24,isHydrostatic=true,shouldAntialias=false);
wvt.initWithRandomFlow(uvMax=1e-3);
wvt.addForcing(WVAdaptiveDamping(wvt));
model = WVModel(wvt);

authorAlongTrackPortableRunBundle( ...
    model,fullfile(fixtureFolder,"matlab-authored-repeating.nc"),"j3", ...
    initialTime=0,integrationFinalTime=100.5,finalTime=10000, ...
    missionEpochSeconds=-21678,sampleIntervalSeconds=1, ...
    checkpointIntervalSeconds=100.5, ...
    fieldNames=["ssh","ssu","ssv"],interpolation="linear", ...
    observerIdentifier="ats4-repeating-observer", ...
    fileIdentifier="repeating",groupIdentifier="ats4-repeating-output", ...
    requestPath=fullfile(fixtureFolder,"matlab-authored-repeating-request.json"), ...
    destinationPath=fullfile(fixtureFolder,"matlab-authored-repeating-output.nc"), ...
    reportPath=fullfile(fixtureFolder,"matlab-authored-repeating-report.json"), ...
    integrationMethod="fixed-rk4",initialStep=10, ...
    fftProvider="reference",threads=1,shouldOverwriteExisting=true);

authorAlongTrackPortableRunBundle( ...
    model,fullfile(fixtureFolder,"matlab-authored-geodetic.nc"),"alg", ...
    initialTime=0,integrationFinalTime=100.5,finalTime=10000, ...
    missionEpochSeconds=-1437.75,sampleIntervalSeconds=1, ...
    checkpointIntervalSeconds=100.5, ...
    fieldNames=["ssh","ssu","ssv"],interpolation="spline", ...
    observerIdentifier="ats4-geodetic-observer", ...
    fileIdentifier="geodetic",groupIdentifier="ats4-geodetic-output", ...
    requestPath=fullfile(fixtureFolder,"matlab-authored-geodetic-request.json"), ...
    destinationPath=fullfile(fixtureFolder,"matlab-authored-geodetic-output.nc"), ...
    reportPath=fullfile(fixtureFolder,"matlab-authored-geodetic-report.json"), ...
    integrationMethod="adaptive-rk23",initialStep=10,maximumStep=60, ...
    relativeTolerance=1e-6,absoluteToleranceScale=1e-9, ...
    fftProvider="reference",threads=1,shouldOverwriteExisting=true);

authorBuiltInBenchmarkBundle(model,fixtureFolder);
end

function authorBuiltInBenchmarkBundle(model,fixtureFolder)
benchmarkFolder = fullfile(fixtureFolder,"benchmark");
if ~isfolder(benchmarkFolder)
    mkdir(benchmarkFolder);
end
sourcePath = fullfile(benchmarkFolder,"matlab-authored-builtin-output.nc");
requestPath = fullfile(benchmarkFolder,"matlab-authored-builtin-output-request.json");
if isfile(sourcePath)
    delete(sourcePath);
end

outputFile = WVModelOutputFile(model,sourcePath,shouldOverwriteExisting=false);
outputCleanup = onCleanup(@() outputFile.closeNetCDFFile());
outputGroup = WVModelOutputGroupEvenlySpaced(model,name="builtin-output", ...
    initialTime=model.t,finalTime=2e-4,outputInterval=5e-5);
outputGroup.addObservingSystem(model.eulerianObservingSystem);
outputFile.addOutputGroup(outputGroup);
times = outputFile.outputTimesForIntegrationPeriod(model.t,model.t);
if ~isequal(times,model.t)
    error("AlongTrackSimulator:InvalidBenchmarkSchedule", ...
        "The built-in benchmark group did not schedule the initial state.");
end
outputFile.writeTimeStepToOutputFile(model.t);
outputFile.closeNetCDFFile();
clear outputCleanup

fileID = netcdf.open(sourcePath,'NC_WRITE');
netcdfCleanup = onCleanup(@() closeNetCDF(fileID));
netcdf.reDef(fileID);
netcdf.putAtt(fileID,netcdf.getConstant('NC_GLOBAL'), ...
    'portableFileIdentifier','primary');
netcdf.endDef(fileID);
netcdf.close(fileID);
clear netcdfCleanup

request = struct( ...
    schemaIdentifier="wave-vortex-run-request-v1",schemaVersion=1, ...
    modelFiles={{"matlab-authored-builtin-output.nc"}}, ...
    integration=struct(method="fixed-rk4",finalTime=2e-4,initialStep=1e-6), ...
    output=struct(policy="create",destinations=containers.Map( ...
        'primary','matlab-authored-builtin-output-result.nc')), ...
    execution=struct(fftProvider="reference",threads=1), ...
    report="matlab-authored-builtin-output-report.json");
writeJSON(requestPath,request);
end

function writeJSON(path,value)
fileID = fopen(path,'wt');
if fileID == -1
    error("AlongTrackSimulator:BenchmarkRequestOpenFailed", ...
        "Could not open '%s' for writing.",path);
end
cleanup = onCleanup(@() fclose(fileID));
fprintf(fileID,'%s\n',jsonencode(value,PrettyPrint=true));
clear cleanup
end

function closeNetCDF(fileID)
try
    netcdf.close(fileID);
catch exception
    if ~contains(exception.message,"Not a valid ID")
        rethrow(exception)
    end
end
end
